### ISSUE TITLE
Downloader on windows fails when file names have in special chars like "?|!"

### ISSUE THREAD

**Issue by yididiyan** [Electrobub/DW_Audio_Downloader#1]
Some of the audio titles contain "?", "|", "!". While saving files with these special character work, it would work fine in Linux. But Windows complains.

**Comment by yididiyan** [comment]
```python
def remove_special_chars(filename):
    """
    Remove special chars like ? ! from filenames as Windows dont allow it
    """
    special_chars = "?!|"
    for char in special_chars:
        filename = filename.replace(char, "")

    return filename
```


Could solve the issue?

**Comment by tpotie** [comment]
Hi @Yididya, thanks a lot for bringing this up! It took a while to get around to it - with everything else going on at the moment.

Please look into the linked PR and let me know.
(The idea was not to remove this information (Question or Exclamation) from the filename - as this affects the intonation of the audio.

Thanks again for bringing it to my attention (and providing a code snippet) please let me know how it goes on a Windows machine :slightly_smiling_face:
